<?php


namespace App\HttpController;


use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Http\Message\UploadFile;

class File extends Controller
{
    function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }

    /*
     * 图片上传
     */
    public function image()
    {
        $request = $this->request();
        /** @var $imgFile UploadFile */
        $imgFile = $request->getUploadedFile('img');
        $this->writeJson(200,$imgFile->getClientMediaType());
    }

    /*
     * 视频上传
     */
    public function radio()
    {
        $request = $this->request();
        /** @var $imgFile UploadFile */
        $imgFile = $request->getUploadedFile('radio');
        $this->writeJson(200,$imgFile->getClientMediaType());
    }
    /*
     * 文件格式验证
     */

}