<?php


namespace App\HttpController;


use EasySwoole\Http\AbstractInterface\Controller;

class Hello extends Controller
{

    private $userid;

    //表示当请求到达的时候第一个会被执行的方式。如果返回False则后面的所有内容都不回执行。常用于拦截，身份鉴定，初始化操作等。
    protected function onRequest(string $action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    protected function gc()
    {
        parent::gc(); // TODO: Change the autogenerated stub
        $this->userid = null; //回收。因userid是私有的所以不回收的话会一直存在
    }

    function index()
    {
        echo 'hello world';
    }
    function test()
    {
        /*
        //向前端网页输出内容
        $this->response()->withHeader('Content-Type','text/html;charset=utf-8');
        $this->response()->write('你好');
        */
        /*
        //前后端分离写接口，向前端返回的内容
        #$this->writeJson(200,['这是返回的结果'],'这是smg');
        */

        // null
        var_dump($this->userid);
        $this->userid=1;
        // 1
        var_dump($this->userid);
    }

    //当action执行结束后调用该方法，可自定义数据回收等逻辑。常用于日志写入或者后置操作
    protected function afterAction(string $actionName): void
    {
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }

    //当请求方法未找到时，自动调用此方法
    protected function actionNotFound(?string $action)
    {
        $class = static::class;
        $this->writeJson(\EasySwoole\Http\Message\Status::CODE_NOT_FOUND,null,"{$class} has not action for {$action}");
    }
}